name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Auth in NuGet
      run: dotnet nuget add source --username Sejoslaw --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DovaOfficial/index.json"
    - name: Restore dependencies
      run: dotnet restore -v diag src/Dova.JDK.JNA.sln
    - name: Build
      run: dotnet build --no-restore -v diag src/Dova.JDK.JNA/Dova.JDK.JNA.csproj
    - name: Test
      run: dotnet test --no-build -v diag src/Dova.JDK.JNA/Dova.JDK.JNA.csproj
    - name: Pack
      run: dotnet pack --configuration Release -v diag src/Dova.JDK.JNA/Dova.JDK.JNA.csproj
    - name: Publish NuGet
      run: dotnet nuget push "src/Dova.JDK.JNA/bin/Release/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
